name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      actions: write

    # Fallback por si el secret no está disponible
    env:
      IMAGE_OWNER: zahir2112

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install deps
        run: npm ci

      - name: Run unit tests
        run: npm test

      # Login a Docker Hub usando el secret si existe, o el fallback
      - name: Docker login
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME || env.IMAGE_OWNER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Definir la imagen (usa secret si existe, o el fallback)
      - name: Define image name
        run: echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME || env.IMAGE_OWNER }}/devops-hola-mundo" >> $GITHUB_ENV

      - name: Extract Docker metadata
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push Docker image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trigger Render deploy (optional)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          if [ -n "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" ]; then
            echo "Triggering Render Deploy Hook..."
            curl -sS -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
            echo "Render deploy hook triggered."
          else
            echo "RENDER_DEPLOY_HOOK_URL no configurado. Saltando deploy."
          fi
